# public/admin/config.yml
backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
local_backend: true

media_library:
  name: cloudinary
  config:
    cloud_name: dueymuhdz
    api_key: 865213366493329
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

editor:
  preview: false

collections:
  # - HOME
  - name: "home"
    label: "Home"
    i18n:
      structure: single_file
      locales: [en, pt]
    folder: "src/pages/home" 
    create: true
    slug: "{{slug}}"
    fields:

      # -- HERO
      - label: "Hero"
        name: "hero"
        widget: "object"
        collapsed: true
        fields: 
          - {label: "Tagline", name: "heroTagline", widget: "markdown"}
          - {label: "Description", name: "heroDescription", widget: "text"}
          - label: "Main Button"
            name: "heroMainButton"
            widget: "object"
            collapsed: true
            fields: 
              - {label: "Active", name: "active", widget: "boolean", default: true}
              - {label: "Label", name: "label", widget: "string"}
              - {label: "Link", name: "link", widget: "string"}
          - label: "Secondary Button"
            name: "SecondaryButton"
            widget: "object"
            collapsed: true
            fields: 
              - {label: "Active", name: "active", widget: "boolean", default: true}
              - {label: "Label", name: "label", widget: "string"}
              - {label: "Link", name: "link", widget: "string"} 



      # - {label: "Hero Tagline", name: "heroTagline", widget: "markdown"}
      # - {label: "Hero Description", name: "heroDescription", widget: "text"}
      # - label: "Hero Main Button"
      #   name: "heroMainButton"
      #   widget: "object"
      #   collapsed: true
      #   fields: 
      #     - {label: "Active", name: "active", widget: "boolean", default: true}
      #     - {label: "Label", name: "label", widget: "string"}
      #     - {label: "Link", name: "link", widget: "string"}
      # - label: "Hero Secondary Button"
      #   name: "heroSecondaryButton"
      #   widget: "object"
      #   collapsed: true
      #   fields: 
      #     - {label: "Active", name: "active", widget: "boolean", default: true}
      #     - {label: "Label", name: "label", widget: "string"}
      #     - {label: "Link", name: "link", widget: "string"}  

      # -- ABOUT
      - {label: "About Title", name: "aboutTitle", widget: "string"}
      - {label: "About Description", name: "aboutDescription", widget: "text"}  
      - label: "About Image"
        name: "aboutImage"
        widget: "image"
        allow_multiple: false
        media_library:
          config:
            multiple: false 

      # -- PROJECTS
      - {label: "Projects Title", name: "projectsTitle", widget: "string"}
      - {label: "Projects Description", name: "projectsDescription", widget: "text"}  
     
      # -- BLOG
      - {label: "Blog Title", name: "blogTitle", widget: "string"}
      - {label: "Blog Description", name: "blogDescription", widget: "text"}

      # -- CONTACT
      - {label: "Contact Title", name: "contactTitle", widget: "string"}
      - {label: "Contact Description", name: "contactDescription", widget: "text"}

  # - PROJECTS
  - name: "projects"
    label: "Projects"
    i18n:
      structure: single_file
      locales: [en, pt]
    folder: "src/pages/projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      # Point to Astro layout
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/ProjectSingle.astro"}
      # Title
      - {label: "Title", name: "title", widget: "string"}
      # Date
      - {label: "Publish Date", name: "date", widget: "datetime"}
      # Tags
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        min: 1
        max: 12
        options: ["Design", "UX", "UI", "Dev", "Migration", "Visual Identity"]
      # Client  
      - {label: "Client", name: "client", widget: "string"}
      # URL
      - {label: "URL", name: "url", widget: "string"}
      # Tech Stack
      - label: "Tech stack"
        name: "techStack"
        widget: "select"
        multiple: true
        min: 1
        max: 12
        options: ["WordPress", "Craft CMS", "Astro", "Sass", "Tailwind", "Netlify", "Svelte", "React", "Preact", "Jquery", ]
      # Description  
      - {label: "Description", name: "description", widget: "markdown"} 
      # Featured Image  
      - label: "Featured Image"
        name: "featuredImage"
        widget: "image"
        allow_multiple: false
        media_library:
          config:
            multiple: false   
      # Images
      - label: "Project Images"
        name: "projectImages"
        widget: "image"
        allow_multiple: true
        media_library:
          config:
            multiple: true
  # ---- BLOG
  - name: "blog"
    label: "Blog"
    i18n:
      structure: single_file
      locales: [en, pt]
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      # Point to Astro layout
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/blogSingle.astro"}
      # Title
      - {label: "Title", name: "title", widget: "string"}
      # Date
      - {label: "Publish Date", name: "date", widget: "datetime"}
      # Author
      - {label: "Author", name: "author", widget: "string", default: ["Pedro Kehl"]}
      # Tags
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        min: 1
        max: 12
        options: ["Design", "Visual Arts", "Random Thoughts", "Dev"]
      # Description  
      - {label: "Description", name: "description", widget: "text"}
      # Body
      - {label: "Body", name: "body", widget: "markdown"}  
      # Featured Image  
      - label: "Featured Image"
        name: "featuredImage"
        widget: "image"
        allow_multiple: false
        media_library:
          config:
            multiple: false