# public/admin/config.yml
backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
local_backend: true

media_library:
  name: cloudinary
  config:
    cloud_name: dueymuhdz
    api_key: 865213366493329
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

editor:
  preview: false

collections:
  # ----- SETTINGS
  - name: 'settings'
    label: 'Settings'
    delete: false
    editor:
      preview: false
    files:
      - name: 'general'
        label: 'Site Settings'
        file: '_data/settings.json'
        description: 'General Site Settings'
        fields:
          - { label: 'Global title', name: 'site_title', widget: 'string' }
          - label: 'Post Settings'
            name: posts
            widget: 'object'
            fields:
              - {
                  label: 'Number of posts on frontpage',
                  name: front_limit,
                  widget: number,
                  min: 1,
                  max: 10,
                }
              - { label: 'Default Author', name: author, widget: string }
              - {
                  label: 'Default Thumbnail',
                  name: thumb,
                  widget: image,
                  class: 'thumb',
                  required: false,
                }

      # ----- AUTHORS
      - name: 'authors'
        label: 'Authors'
        file: '_data/authors.json'
        description: 'Author descriptions'
        fields:
          - name: authors
            label: Authors
            label_singular: 'Author'
            widget: list
            fields:
              - { label: 'Name', name: 'name', widget: 'string', hint: 'First and Last' }
              - { label: 'Description', name: 'description', widget: 'markdown' }
  
  # ----- HOME
  - name: 'home'
    label: 'Home'
    delete: false
    editor:
      preview: false
    files:

      # ---- HERO
      - name: 'hero'
        label: 'Hero'
        file: 'src/pages/singular/hero.md'
        description: 'Hero section settings'
        fields:
          - {label: "Tagline", name: "tagline", widget: "string"}
          - {label: "Main Tagline", name: "mainTagline", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - name: buttons
            label: Buttons
            label_singular: 'Button'
            widget: list
            fields:
              - { label: 'Label', name: 'label', widget: 'string' }
              - { label: 'Link', name: 'link', widget: 'string' }
              - label: "Type"
                name: "type"
                widget: "select"
                options: ["Primary", "Secondary", "Alert"]
          # - label: "Main Button"
          #   name: "mainButton"
          #   widget: "object"
          #   collapsed: true
          #   fields: 
          #     - {label: "Active", name: "active", widget: "boolean", default: true}
          #     - {label: "Label", name: "label", widget: "string"}
          #     - {label: "Link", name: "link", widget: "string"}
          # - label: "Secondary Button"
          #   name: "secondaryButton"
          #   widget: "object"
          #   collapsed: true
          #   fields:
          #     - {label: "Active", name: "active", widget: "boolean", default: true}
          #     - {label: "Label", name: "label", widget: "string"}
          #     - {label: "Link", name: "link", widget: "string"}

      # ---- ABOUT
      - name: 'about'
        label: 'About'
        file: 'src/pages/singular/about.md'
        description: 'About section settings'
        fields: 
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Description", name: "description", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}  
        - label: "Image"
          name: "image"
          widget: "image"
          allow_multiple: false
          media_library:
            config:
              multiple: false

      # ---- PROJECTS
      - name: 'projects'
        label: 'Projects'
        file: 'src/pages/singular/projects.md'
        description: 'Projects section settings'
        fields: 
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Description", name: "description", widget: "string"}
        - {label: "Number of projects on the homepage", name: "postsNum", widget: "number", default: 3, min: 3, max: 12}

      # ---- BLOG
      - name: 'blog'
        label: 'Blog'
        file: 'src/pages/singular/blog.md'
        description: 'Blog section settings'
        fields: 
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Description", name: "description", widget: "string"} 
        - {label: "Number of posts on the homepage", name: "postsNum", widget: "number", default: 3, min: 3, max: 12} 

      # ---- CONTACT
      - name: 'contact'
        label: 'Contact'
        file: 'src/pages/singular/contact.md'
        description: 'Contact section settings'
        fields: 
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Description", name: "description", widget: "string"}

  # ----- PROJECTS
  - name: "projects"
    label: "Projects"
    i18n:
      structure: single_file
      locales: [en, pt]
    folder: "src/pages/projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      # Point to Astro layout
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/ProjectSingle.astro"}
      # Title
      - {label: "Title", name: "title", widget: "string"}
      # Date
      - {label: "Publish Date", name: "date", widget: "datetime"}
      # Tags
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        min: 1
        max: 12
        options: ["Design", "UX", "UI", "Dev", "Migration", "Visual Identity"]
      # Client  
      - {label: "Client", name: "client", widget: "string"}
      # URL
      - {label: "URL", name: "url", widget: "string"}
      # Tech Stack
      - label: "Tech stack"
        name: "techStack"
        widget: "select"
        multiple: true
        min: 1
        max: 12
        options: ["WordPress", "Craft CMS", "Astro", "Sass", "Tailwind", "Netlify", "Svelte", "React", "Preact", "Jquery", ]
      # Description  
      - {label: "Description", name: "description", widget: "markdown"} 
      # Featured Image  
      - label: "Featured Image"
        name: "featuredImage"
        widget: "image"
        allow_multiple: false
        media_library:
          config:
            multiple: false   
      # Images
      - label: "Project Images"
        name: "projectImages"
        widget: "image"
        allow_multiple: true
        media_library:
          config:
            multiple: true

  # ----- BLOG
  - name: "blog"
    label: "Blog"
    i18n:
      structure: single_file
      locales: [en, pt]
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      # Point to Astro layout
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/blogSingle.astro"}
      # Title
      - {label: "Title", name: "title", widget: "string"}
      # Date
      - {label: "Publish Date", name: "date", widget: "datetime"}
      # Author
      - {label: "Author", name: "author", widget: "string", default: ["Pedro Kehl"]}
      # Tags
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        min: 1
        max: 12
        options: ["Design", "Visual Arts", "Random Thoughts", "Dev"]
      # Description  
      - {label: "Description", name: "description", widget: "text"}
      # Body
      - {label: "Body", name: "body", widget: "markdown"}  
      # Featured Image  
      - label: "Featured Image"
        name: "featuredImage"
        widget: "image"
        allow_multiple: false
        media_library:
          config:
            multiple: false
