# public/admin/config.yml
backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
local_backend: true

media_library:
  name: cloudinary
  config:
    cloud_name: ppkehl
    api_key: 865213366493329
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [en, pt, it]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

editor:
  preview: false

collections:
  # ----- SETTINGS
  - name: 'settings'
    label: 'Settings'
    delete: false
    editor:
      preview: false
    files:
      - name: 'general'
        label: 'Site Settings'
        file: 'src/data/settings/generalSettings.json'
        description: 'General Site Settings'
        fields:
          - { label: 'Global title', name: 'site_title', widget: 'string' }
      - name: 'colorSchemes'
        label: 'Color Schemes'
        file: 'src/data/settings/colorSchemes.json'
        description: 'Color Schemes'
        fields:
          - name: colorSchemes
            label: Color Schemes
            label_singular: 'Color Scheme'
            widget: list
            fields:
              - { label: 'Scheme Name', name: 'schemeName', widget: 'string'}
              - label: "Colors"
                name: "colors"
                widget: "object"
                fields:
                  - { label: 'Primary', name: 'primary', widget: 'color', allowInput: true }
                  - { label: 'Secondary', name: 'secondary', widget: 'color', allowInput: true }
                  - { label: 'Tertiary', name: 'tertiary', widget: 'color', allowInput: true }
                  - { label: 'Alert', name: 'alert', widget: 'color', allowInput: true }
                  - { label: 'Danger', name: 'danger', widget: 'color', allowInput: true }            
              

      # ----- AUTHORS
      - name: 'authors'
        label: 'Authors'
        file: 'src/data/settings/authors.json'
        description: 'Author descriptions'
        fields:
          - name: authors
            label: Authors
            label_singular: 'Author'
            widget: list
            fields:
              - { label: 'Name', name: 'name', widget: 'string'}
              - { label: 'Description', name: 'description', widget: 'markdown' }
  
  # ----- HOME
  - name: 'home'
    label: 'Home'
    delete: false
    editor:
      preview: false
    files:

      # ---- HERO
      - name: 'hero'
        label: 'Hero'
        file: 'src/pages/singular/hero.md'
        description: 'Hero section settings'
        fields:
          - {label: "Active", name: "active", widget: "boolean", default: true}
          - {label: "Tagline", name: "tagline", widget: "string"}
          - {label: "Main Tagline", name: "body", widget: "markdown"}
          - {label: "Description", name: "description", widget: "text"}
          - name: buttons
            label: Buttons
            label_singular: 'Button'
            widget: list
            fields:
              - { label: 'Label', name: 'label', widget: 'string' }
              - { label: 'Link', name: 'link', widget: 'string' }
              - label: "Type"
                name: "type"
                widget: "select"
                options: ["Primary", "Secondary", "Tertiary", "Alert", "Danger"]

      # ---- ABOUT
      - name: 'about'
        label: 'About'
        file: 'src/pages/singular/about.md'
        description: 'About section settings'
        fields: 
        - {label: "Active", name: "active", widget: "boolean", default: true}
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Description", name: "description", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}  
        - label: "Image"
          name: "image"
          widget: "image"
          allow_multiple: false
          media_library:
            config:
              multiple: false

      # ---- PROJECTS
      - name: 'projects'
        label: 'Projects'
        file: 'src/pages/singular/projects.md'
        description: 'Projects section settings'
        fields: 
        - {label: "Active", name: "active", widget: "boolean", default: true}
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Description", name: "description", widget: "string"}
        - {label: "Number of projects on the homepage", name: "postsNum", widget: "number", default: 3, min: 0, max: 12}

      # ---- BLOG
      - name: 'blog'
        label: 'Blog'
        file: 'src/pages/singular/blog.md'
        description: 'Blog section settings'
        fields: 
        - {label: "Active", name: "active", widget: "boolean", default: true}
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Description", name: "description", widget: "string"} 
        - {label: "Number of posts on the homepage", name: "postsNum", widget: "number", default: 4, min: 0, max: 12} 

      # ---- CONTACT
      - name: 'contact'
        label: 'Contact'
        file: 'src/pages/singular/contact.md'
        description: 'Contact section settings'
        fields: 
        - {label: "Active", name: "active", widget: "boolean", default: true}
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Description", name: "description", widget: "string"}

  # ----- PROJECTS
  - name: "projects"
    label: "Projects"
    # i18n:
    #   structure: single_file
    #   locales: [en, pt]
    folder: "src/pages/projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      # Point to Astro layout
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/ProjectSingle.astro"}
      # Title
      - {label: "Title", name: "title", widget: "string"}
      # Date
      - {label: "Publish Date", name: "date", widget: "datetime"}
      # Tags
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        allow_add: true
        min: 1
        max: 12
        options: ["Design", "UX", "UI", "Frontend", "Dev", "Migration", "Visual Identity"]
      # Client  
      - {label: "Client", name: "client", widget: "string"}
      # URL
      - {label: "URL", name: "url", widget: "string"}
      # Tech Stack
      - label: "Tech stack"
        name: "techStack"
        widget: "select"
        multiple: true
        allow_add: true
        min: 1
        max: 12
        options: ["WordPress", "Craft CMS", "Astro", "Sass", "Tailwind", "Netlify", "Svelte", "React", "Preact", "Jquery", "GreenSock", "JavaScript"]
      # Description  
      - {label: "Description", name: "body", widget: "markdown"} 
      # Featured Image  
      - label: "Featured Image"
        name: "featuredImage"
        widget: "image"
        allow_multiple: false
        media_library:
          config:
            multiple: false   
      # Images
      - label: "Project Images"
        name: "projectImages"
        widget: "image"
        allow_multiple: true
        media_library:
          config:
            multiple: true

  # ----- BLOG
  - name: "blog"
    label: "Blog"
    # i18n:
    #   structure: single_file
    #   locales: [en, pt]
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      # Point to Astro layout
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/BlogSingle.astro"}
      # Title
      - {label: "Title", name: "title", widget: "string"}
      # Date
      - {label: "Publish Date", name: "date", widget: "datetime"}
      # Author
      - {label: "Author", name: "author", widget: "string", default: "Pedro Kehl"}
      # Tags
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        min: 1
        max: 12
        options: ["Design", "Visual Arts", "Random Thoughts", "Dev"]
      # Description  
      - {label: "Description", name: "description", widget: "text"}
      # Body
      - {label: "Post", name: "body", widget: "markdown"}  
      # Featured Image  
      - label: "Featured Image"
        name: "featuredImage"
        widget: "image"
        allow_multiple: false
        media_library:
          config:
            multiple: false


  # ----- TEST
  - name: "test"
    label: "Test"
    i18n:
      structure: multiple_folders
      locales: [en, pt, it]
    folder: 'src/data/test'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      # Point to Astro layout
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/BlogSingle.astro"}
      # Title
      - {label: "Title", name: "title", widget: "string", i18n: true }
      # Slug
      - {label: "Slug", name: "slug", widget: "string", i18n: true }
      # Date
      - {label: "Publish Date", name: "date", widget: "datetime", i18n: duplicate }   
      # Body
      - {label: "Post", name: "body", widget: "markdown", i18n: true }      
